# For more information: https://laravel.com/docs/sail
version: '3'
services:
    nginx:
        image: nginx:1.21.5-alpine
        ports:
            - 80:80
        networks:
            sail:
                ipv4_address: 172.27.0.2
        volumes:
            - ./docker/nginx.conf:/etc/nginx/nginx.conf
        container_name: myweb-proxy
        depends_on:
            - laravel
            - mysql
    laravel:
        build:
            context: .
            dockerfile: docker/Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        container_name: laravel_app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:8080'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
        links:
            - mysql
        volumes:
            - './routes:/var/www/html/routes'
            - './app:/var/www/html/app'
            - './public:/var/www/html/public'
            - './storage/app/public/photos:/var/www/html/storage/app/public/photos'
            - './resources:/var/www/html/resources'
            - './database:/var/www/html/database'
        networks:
            sail:
                ipv4_address: 172.27.0.3
        depends_on:
            - mysql
    mysql:
        build:
            context: .
            dockerfile: docker/mysql/Dockerfile
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mysql:/var/lib/mysql'
        container_name: mysql_app
        networks:
            sail:
                ipv4_address: 172.27.0.4
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
networks:
    sail:
        ipam:
            driver: default
            config:
                - subnet: 172.27.0.0/16
    out-network:
        driver: bridge
volumes:
    mysql:
        driver: local
